SELECT COUNT(SOHD) N'Số lượng hóa đơn'
FROM HOADON HD ,KHACHHANG KH
WHERE HD.MAKH = KH.MAKH AND NGDK IS NULL;

--CAU 21
SELECT COUNT(DISTINCT MASP) SLSP
FROM HOADON HD, CTHD
WHERE HD.SOHD = CTHD.SOHD AND YEAR(NGHD) = 2006;

--cau 22
SELECT MAX(TRIGIA) TRIGIA_LONNHAT, MIN(TRIGIA) TRIGIA_NHONHAT
FROM HOADON;

--CAU 23
SELECT AVG(TRIGIA) TRIGIA_TRUNGBINH
FROM HOADON
WHERE YEAR(NGHD) = 2006;

--CAU 24
SELECT SUM(TRIGIA) TONGDOANHTHU
FROM HOADON
WHERE YEAR(NGHD) = 2006;

--CAU 25
SELECT SOHD
FROM HOADON
WHERE YEAR(NGHD) = 2006 AND TRIGIA >= ALL(SELECT TRIGIA 
											FROM HOADON		
											WHERE YEAR(NGHD) =2006);

-- CAU 26
SELECT HOTEN
FROM KHACHHANG KH, HOADON HD
WHERE KH.MAKH = HD.MAKH
	AND YEAR(NGHD) = 2006
	AND TRIGIA = (SELECT MAX(TRIGIA)
					FROM HOADON
					WHERE YEAR(NGHD) = 2006);

--CAU 27
SELECT TOP 3 MAKH, HOTEN
FROM KHACHHANG
ORDER BY DOANHSO DESC

--CAU 28
SELECT MASP,TENSP
FROM SANPHAM
WHERE GIA IN (SELECT DISTINCT TOP 3 GIA
				FROM SANPHAM
				ORDER BY GIA DESC);

--cau 29
SELECT MASP,TENSP
FROM SANPHAM
WHERE NUOCSX = 'Thai Lan' AND GIA IN (SELECT DISTINCT TOP 3 GIA
										FROM SANPHAM
										ORDER BY GIA DESC);

--CAU 30
SELECT MASP,TENSP
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc' AND GIA IN (SELECT DISTINCT TOP 3 GIA
										FROM SANPHAM
										WHERE NUOCSX = 'Trung Quoc'
										ORDER BY GIA DESC);
-- cau 32
SELECT COUNT(MASP) AS SLSP_TQ
FROM SANPHAM
WHERE NUOCSX = 'Trung Quoc';

--CAU 33
SELECT NUOCSX, COUNT(MASP) SLSP
FROM SANPHAM
GROUP BY NUOCSX 

--CAU 34
SELECT NUOCSX, MAX(GIA) GIA_MAX , MIN(GIA) GIA_MIN, AVG(GIA) GIA_TB
FROM SANPHAM
GROUP BY NUOCSX;

-- CAU 35
SELECT NGHD , SUM(TRIGIA) DOANHTHU
FROM HOADON
GROUP BY NGHD;

--CAU 36
SELECT MASP,SUM(SL) SLSP
FROM HOADON HD,CTHD CT
WHERE HD.SOHD = CT.SOHD AND 
		MONTH(NGHD) = 10 AND YEAR(NGHD) =2006
GROUP BY MASP;

--CAU 37
SELECT MONTH(NGHD) THANG, SUM(TRIGIA) DOANHTHU
FROM HOADON
WHERE YEAR(NGHD) = 2006
GROUP BY MONTH(NGHD); 

-- cau 38
SELECT SOHD
FROM CTHD
GROUP BY SOHD
HAVING COUNT(DISTINCT MASP) >=4

--CAU 39
SELECT SOHD
FROM CTHD, SANPHAM SP
WHERE CTHD.MASP = SP.MASP
	AND NUOCSX = 'Viet Nam'
GROUP BY SOHD
HAVING COUNT(DISTINCT CTHD.MASP) >= 3;

--CAU 40
SELECT KH.MAKH,HOTEN
FROM KHACHHANG KH, HOADON HD
WHERE KH.MAKH = HD.MAKH 
GROUP BY KH.MAKH,HOTEN
HAVING COUNT(SOHD) >= ALL (SELECT COUNT(SOHD)
							FROM HOADON
							GROUP BY MAKH);

--CAU 41
SELECT MONTH(NGHD) THANG 
FROM HOADON
WHERE YEAR(NGHD) = 2006
GROUP BY MONTH(NGHD)
HAVING SUM(TRIGIA) >= ALL(SELECT SUM(TRIGIA)
							FROM HOADON
							WHERE YEAR(NGHD) = 2006
							GROUP BY MONTH(NGHD));
--CAU 42
SELECT SP.MASP, TENSP
FROM CTHD CT, SANPHAM SP, HOADON HD
WHERE CT.MASP = SP.MASP AND CT.SOHD = HD.SOHD AND YEAR(HD.NGHD) =2006
GROUP BY SP.MASP,TENSP
HAVING SUM(SL) <= ALL(SELECT SUM(SL)
						FROM CTHD CT, HOADON HD
						WHERE CT.SOHD = HD.SOHD AND YEAR(HD.NGHD) =2006
						GROUP BY CT.MASP);



--cau 44
SELECT NUOCSX
FROM SANPHAM
GROUP BY NUOCSX
HAVING COUNT(DISTINCT GIA) >= 3;


