--cau 12 --
SELECT DISTINCT SOHD
FROM CTHD
WHERE MASP IN ('BB01','BB02') AND SL BETWEEN 10 AND 20;

--cau 13 --
SELECT SOHD
FROM CTHD
WHERE MASP = 'BB01'AND (SL BETWEEN 10 AND 20)
INTERSECT -- (PHEP GIAO) --
SELECT SOHD
FROM CTHD
WHERE MASP = 'BB02'AND (SL BETWEEN 10 AND 20);

-- CAU 14 --
SET DATEFORMAT DMY
SELECT DISTINCT (SP.MASP),TENSP
FROM SANPHAM SP, CTHD CT, HOADON HD
WHERE SP.MASP = CT.MASP AND CT.SOHD = HD.SOHD AND (NUOCSX ='Trung Quoc' OR NGHD = '1/1/2007');

-- CAU 15 --

--CACH 2 --
SELECT MASP,TENSP
FROM SANPHAM
WHERE MASP NOT IN (SELECT MASP 
					FROM CTHD);

--cau 16--

--CACH 2
SELECT MASP,TENSP
FROM SANPHAM 
WHERE MASP NOT IN (SELECT MASP 
					FROM HOADON HD JOIN CTHD CT
					ON HD.SOHD = CT.SOHD
					WHERE YEAR(NGHD) = 2006);

-- CAU 17
SELECT MASP,TENSP
FROM SANPHAM 
WHERE MASP NOT IN (SELECT MASP 
					FROM HOADON HD JOIN CTHD CT
					ON HD.SOHD = CT.SOHD
					WHERE YEAR(NGHD) = 2006) AND NUOCSX = 'Trung Quoc' ;

-- cau 18
SELECT SOHD
FROM HOADON HD
WHERE NOT EXISTS (
					SELECT * 
					FROM SANPHAM SP
					WHERE NUOCSX = 'Singapore' AND NOT EXISTS (
							SELECT *
							FROM CTHD CT
							WHERE CT.SOHD = HD.SOHD AND SP.MASP = CT.MASP
						)
	);

--cau 19
SELECT SOHD
FROM HOADON HD
WHERE YEAR(NGHD)=2006 AND NOT EXISTS (
					SELECT * 
					FROM SANPHAM SP
					WHERE NUOCSX = 'Singapore' AND NOT EXISTS (
							SELECT *
							FROM CTHD CT
							WHERE CT.SOHD = HD.SOHD AND SP.MASP = CT.MASP
						)
	);