CREATE DATABASE QLGV;

USE QLGV;

-- Câu 1 --
CREATE TABLE LOP (
	MALOP char(3) PRIMARY KEY,
	TENLOP varchar(40),
	TRGLOP char(5),
	SISO tinyint,
	MAGVCN char(4)
);


CREATE TABLE HOCVIEN (
	MAHV char(5) PRIMARY KEY,
	HO varchar(40),
	TEN varchar(10),
	NGSINH smalldatetime,
	GIOITINH varchar(3),
	NOISINH varchar(40),
	MALOP char(3)
);

CREATE TABLE KHOA (
	MAKHOA varchar(4) PRIMARY KEY,
	TENKHOA varchar(40),
	NGTLAP smalldatetime,
	TRGKHOA char(4)
);

CREATE TABLE MONHOC (
	MAMH varchar(10) PRIMARY KEY,
	TENMH varchar(40),
	TCLT tinyint,
	TCTH tinyint,
	MAKHOA varchar(4)
);

CREATE TABLE DIEUKIEN (
	MAMH varchar(10),
	MAMH_TRUOC varchar(10),
	constraint PK_DK PRIMARY KEY(MAMH,MAMH_TRUOC)
);

CREATE TABLE GIAOVIEN (
	MAGV char(4) PRIMARY KEY,
	HOTEN varchar(40),
	HOCVI varchar(10),
	HOCHAM varchar(10),
	GIOITINH varchar(3),
	NGSINH smalldatetime,
	NGVL smalldatetime,
	HESO numeric(4,2),
	MUCLUONG money,
	MAKHOA varchar(4)
);


CREATE TABLE GIANGDAY (
	MALOP char(3),
	MAMH varchar(10),
	MAGV char(4),
	HOCKY tinyint,
	NAM smallint,
	TUNGAY smalldatetime,
	DENNGAY smalldatetime,
	constraint PK_GD PRIMARY KEY(MALOP,MAMH)
);

CREATE TABLE KETQUATHI (
	MAHV char(5),
	MAMH varchar(10),
	LANTHI tinyint,
	NGTHI smalldatetime,
	DIEM numeric(4,2),
	KQUA varchar(10),
	constraint PK_KQT PRIMARY KEY(MAHV,MAMH,LANTHI)
);

ALTER TABLE HOCVIEN ADD FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);

ALTER TABLE LOP ADD FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN(MAHV)

ALTER TABLE LOP ADD FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV);

ALTER TABLE KHOA ADD FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV);

ALTER TABLE MONHOC ADD FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);

ALTER TABLE DIEUKIEN ADD FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH);

ALTER TABLE DIEUKIEN ADD FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH);

ALTER TABLE GIAOVIEN ADD FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);

ALTER TABLE GIANGDAY ADD FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);

ALTER TABLE GIANGDAY ADD FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH);

ALTER TABLE GIANGDAY ADD FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV);

ALTER TABLE KETQUATHI ADD FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV);

ALTER TABLE KETQUATHI ADD FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH);

-- Thêm vào 3 thuộc cột GHICHU,DIEMTB,XEPLOAI vào bảng HOCVIEN -- 
ALTER TABLE HOCVIEN ADD GHICHU varchar(100);

ALTER TABLE HOCVIEN ADD DIEMTB decimal(4,2);

ALTER TABLE HOCVIEN ADD XEPLOAI varchar(20);

-- Câu 2 -- 
ALTER TABLE HOCVIEN ADD CONSTRAINT CK_MAHV CHECK  (LEFT(MAHV,3) = MALOP);

-- Câu 3 --
ALTER TABLE HOCVIEN ADD CONSTRAINT CK_GIOITINH CHECK (GIOITINH IN ('Nam','Nu'));
ALTER TABLE GIAOVIEN ADD CONSTRAINT CK_GIOITINH CHECK (GIOITINH IN ('Nam','Nu'));

-- Câu 4 --
ALTER TABLE KETQUATHI ADD CONSTRAINT CK_DIEM CHECK (DIEM BETWEEN 0 AND 10);
ALTER TABLE KETQUATHI ALTER COLUMN DIEM decimal(4,2);

-- Câu 5 --
ALTER TABLE KETQUATHI ADD CONSTRAINT CK_KQUA CHECK ((KQUA ='Dat' AND (DIEM BETWEEN 5 AND 10)) OR (KQUA ='Khong dat' AND (DIEM<5)));

-- Câu 6 --
ALTER TABLE KETQUATHI ADD CONSTRAINT CK_LANTHI CHECK ( LANTHI <=3);

-- Câu 7 --
ALTER TABLE GIANGDAY ADD CONSTRAINT CK_HOCKY CHECK (HOCKY BETWEEN 1 AND 3);

-- Câu 8 --
ALTER TABLE GIAOVIEN ADD CONSTRAINT CK_HOCVI CHECK (HOCVI IN ('CN','KS','ThS','TS','PTS'));