CREATE DATABASE DE_C

USE DE_C

CREATE TABLE KHACHHANG (
	MAKH varchar(5) PRIMARY KEY,
	HTKH varchar(100),
	CMND int,
	SDT int,
	LOAIKH varchar(20),
	GIAMGIA float
);

CREATE TABLE DICHVU (
	MADV varchar(4) PRIMARY KEY,
	TENDV varchar(100),
	GIA int
);

CREATE TABLE HOPDONG (
	SOHD int PRIMARY KEY,
	MAKH varchar(5),
	TENTC varchar(20),
	NGLAP smalldatetime,
	NGKT smalldatetime
);

CREATE TABLE CTHD (
	SOHD int ,
	MADV varchar(4),
	NGSD smalldatetime
	constraint pk PRIMARY KEY (SOHD,MADV)
);

INSERT INTO KHACHHANG VALUES ('KH001' ,'Bui Hoang Nhat Phuong', 357753735 ,0761231234,' VIP', 10);
INSERT INTO KHACHHANG VALUES ('KH002' ,'Bui Van Tri ',246264426, 0523453456, 'Than thiet',5);
INSERT INTO KHACHHANG VALUES ('KH003' ,'Le Duy Thanh Cong' ,197917791 ,0354321508 ,'Thuong' ,0);

INSERT INTO DICHVU VALUES('DV01', 'Tam rua', 100000);
INSERT INTO DICHVU VALUES('DV02', 'Nghe nhac', 45000);
INSERT INTO DICHVU VALUES('DV03',' Mat xa thu gian', 150000);

SET DATEFORMAT DMY
INSERT INTO HOPDONG VALUES (1,'KH001',' Boss',' 09/11/2018',' 16/11/2018');
INSERT INTO HOPDONG VALUES (2,'KH002',' Den',' 22/12/2018',' 25/12/2018');
INSERT INTO HOPDONG VALUES (3,'KH001',' Map',' 14/12/2018',' 28/12/2018');

SET DATEFORMAT DMY
INSERT INTO CTHD VALUES (1 ,'DV01','10/11/2018');
INSERT INTO CTHD VALUES (2,'DV02','23/12/2018');
INSERT INTO CTHD VALUES (1 ,'DV03','28/12/2018');

ALTER TABLE CTHD ADD CONSTRAINT FK_SOHD FOREIGN KEY (SOHD) REFERENCES HOPDONG(SOHD)
ALTER TABLE CTHD ADD CONSTRAINT FK_MADV FOREIGN KEY (MADV) REFERENCES DICHVU(MADV)

ALTER TABLE HOPDONG ADD CONSTRAINT FK_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)

--CAU 3
ALTER TABLE KHACHHANG ADD CONSTRAINT CK CHECK ((LOAIKH ='Vip' AND GIAMGIA = 10)OR LOAIKH <>'Vip');

--cau 5
SELECT SOHD
FROM HOPDONG
WHERE MONTH(NGLAP) = 12 AND YEAR (NGLAP) = 2018
ORDER BY NGKT DESC

-- CAU 6

SELECT TENDV, GIA
FROM DICHVU D, CTHD C
WHERE D.MADV = C.MADV AND YEAR(NGSD) = 2018
GROUP BY D.MADV, TENDV, GIA
HAVING COUNT(NGSD) <= ALL (
	SELECT COUNT(NGSD)
	FROM CTHD
	WHERE YEAR(NGSD) = 2018
	GROUP BY MADV
);

--CAU 7
SELECT MADV
FROM DICHVU
EXCEPT
SELECT MADV
FROM CTHD C, KHACHHANG K ,HOPDONG H
WHERE C.SOHD = H.SOHD AND K.MAKH = H.MAKH AND
			LOAIKH IN('Thuong','Than thiet');
-- CAU 8
SELECT MAKH, HTKH
FROM KHACHHANG
WHERE NOT EXISTS (SELECT *
					FROM DICHVU
					WHERE (GIA >100000) 
						
					)