--CAU 19 
SELECT MAKHOA, TENKHOA
FROM KHOA
WHERE NGTLAP <= ALL (SELECT NGTLAP
					FROM KHOA);
--CAU 20
SELECT COUNT(*) AS SL_GS_PGS
FROM GIAOVIEN
WHERE HOCHAM IN ('GS','PGS');

--CAU 21
SELECT MAKHOA,COUNT(*) AS SL
FROM GIAOVIEN
WHERE HOCVI IN ('CN','KS','ThS','TS','PTS')
GROUP BY MAKHOA;

--CAU 22
SELECT MAMH, KQUA, COUNT(MAHV) SL
FROM KETQUATHI
GROUP BY MAMH, KQUA;

--CAU 23
SELECT MAGV,HOTEN
FROM GIAOVIEN
WHERE MAGV IN ( SELECT DISTINCT MAGV
				FROM GIANGDAY GD JOIN LOP L
				ON GD.MALOP = L.MALOP
				WHERE GD.MAGV = L.MAGVCN); 
-- CAU 24
SELECT HO +' '+ TEN HOTEN
FROM HOCVIEN HV JOIN LOP L
ON HV.MAHV = L.TRGLOP
WHERE SISO = (SELECT MAX(SISO) FROM LOP);

--cau 26
SELECT MAHV, HO +' '+ TEN HOTEN
FROM HOCVIEN
WHERE MAHV IN (
		SELECT MAHV
		FROM KETQUATHI
		WHERE DIEM IN(9,10)
		GROUP BY MAHV
		HAVING COUNT(MAHV) >= ALL(SELECT COUNT(MAHV)
									FROM KETQUATHI
									WHERE DIEM IN(9,10)
									GROUP BY MAHV)
);

--CAU 27
SELECT LEFT(A.MAHV, 3) MALOP, A.MAHV, HO + ' ' + TEN HOTEN FROM (
	SELECT MAHV, RANK () OVER (ORDER BY COUNT(MAMH) DESC) RANK_MH FROM KETQUATHI KQ 
	WHERE DIEM BETWEEN 9 AND 10
	GROUP BY KQ.MAHV
) A INNER JOIN HOCVIEN HV
ON A.MAHV = HV.MAHV
WHERE RANK_MH IN(1,2,3)
GROUP BY LEFT(A.MAHV, 3), A.MAHV, HO, TEN

-- CAU 28
SELECT HOCKY, NAM, MAGV, COUNT(MAMH) SOMH, COUNT(MALOP) SOLOP FROM GIANGDAY
GROUP BY HOCKY, NAM, MAGV

--CAU 29
SELECT HOCKY, NAM, A.MAGV, HOTEN FROM (
	SELECT HOCKY, NAM, MAGV, RANK() OVER (PARTITION BY HOCKY, NAM ORDER BY COUNT(MAMH) DESC) RANK_SOMH FROM GIANGDAY
	GROUP BY HOCKY, NAM, MAGV
) A INNER JOIN GIAOVIEN GV 
ON A.MAGV = GV.MAGV
WHERE RANK_SOMH = 1

-- CAU 30
SELECT A.MAMH, TENMH FROM (
	SELECT MAMH, RANK() OVER (ORDER BY COUNT(MAHV) DESC) RANK_SOHV FROM KETQUATHI
	WHERE LANTHI = 1 AND KQUA = 'Khong Dat'
	GROUP BY MAMH
) A INNER JOIN MONHOC MH
ON A.MAMH = MH.MAMH
WHERE RANK_SOHV = 1

--CAU 31
SELECT A.MAHV, HO + ' ' + TEN HOTEN FROM (
	SELECT MAHV, COUNT(KQUA) SODAT FROM KETQUATHI 
	WHERE LANTHI = 1 AND KQUA = 'Dat'
	GROUP BY MAHV
	INTERSECT
	SELECT MAHV, COUNT(MAMH) SOMH FROM KETQUATHI 
	WHERE LANTHI = 1
	GROUP BY MAHV
) A INNER JOIN HOCVIEN HV
ON A.MAHV = HV.MAHV