-- CAU 11
CREATE TRIGGER trg01_ins_HOADON ON HOADON
FOR INSERT,UPDATE
AS
BEGIN
DECLARE @MAKH varchar(4);
DECLARE @NGHD smalldatetime;
 SELECT @MAKH=MAKH,@NGHD=NGHD FROM INSERTED
DECLARE @NGDK smalldatetime;
SELECT @NGDK=NGDK FROM KHACHHANG
 WHERE MAKH=@MAKH

IF (@NGDK>@NGHD)
	 BEGIN
		PRINT 'ERROR: ngay dang ky phai < ngay hoa don '
		ROLLBACK TRAN
	 END
ELSE
	 BEGIN
		PRINT 'HOA DON DA THEM THANH CONG'
	 END
END

-- CAU 12
CREATE TRIGGER CheckSaleDate ON HOADON
FOR INSERT,UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM inserted i
        JOIN NHANVIEN NV ON i.MANV = NV.MANV
        WHERE i.NGHD < NV.NGVL
    )
    BEGIN
        RAISERROR ('Ngày bán hàng phải lớn hơn hoặc bằng ngày nhân viên vào làm!', 16, 1)
        ROLLBACK TRANSACTION
    END
END;

-- CAU 13

 CREATE TRIGGER XOA_CTHD ON CTHD
 FOR DELETE,UPDATE
 AS
 BEGIN
	DECLARE @SOHD INT,@SLCL INT
	SELECT @SOHD = SOHD FROM deleted
	SELECT @SLCL = COUNT(*) FROM CTHD WHERE SOHD = @SOHD
	IF @SLCL <1
	BEGIN
		PRINT 'Moi hoa don phai co it nhat 1 CTHD'
		ROLLBACK TRAN
	END
	ELSE
		PRINT 'Xoa CTHD Thanh cong'
 END