CREATE DATABASE De_A;

USE De_A;

CREATE TABLE KHACHTHUE (
	MAKT varchar(6) PRIMARY KEY,
	TENKT varchar(100),
	NGSINH smalldatetime,
	CMND int,
	DIACHI varchar(20)
);

CREATE TABLE XEMAY (
	MAXE varchar(5) PRIMARY KEY,
	TENXE varchar(100),
	DUNGTICH int,
	GIA float,
	TINHTRANG varchar(20)
);

CREATE TABLE E_BILL (
	SOHD int PRIMARY KEY,
	NGTHUE smalldatetime,
	NGTRA smalldatetime,
	MAKT varchar(6)
);

CREATE TABLE CTTHUE (
	SOHD int,
	MAXE varchar(5),
	SL int,
	constraint pk_sohd_maxe PRIMARY KEY (SOHD,MAXE)
);


SET DATEFORMAT DMY
INSERT INTO KHACHTHUE VALUES ('KT0083','Le Thi Phuong Khanh','09/02/1999',273656107,'BRVT')
INSERT INTO KHACHTHUE VALUES ('KT0329','Nguyen Vinh Hai','03/01/1999',221421550,'Phu Yen')
INSERT INTO KHACHTHUE VALUES ('KT0137','Le Hoang Long','07/07/1999',184361699,'Ha Tinh')


INSERT INTO XEMAY VALUES('X1942','Yamaha Exciter',150,80000,'Con')
INSERT INTO XEMAY VALUES('X2719','Honda SH 150',153,100000,'Gan het')
INSERT INTO XEMAY VALUES('X2739','Suzuki Raider',147,70000,'Het')

SET DATEFORMAT DMY
INSERT INTO E_BILL VALUES(1,'01/11/2018','10/11/2018','KT0329')	
INSERT INTO E_BILL VALUES(2,'07/12/2018','10/12/2018','KT0329')	
INSERT INTO E_BILL VALUES(3,'18/12/2018','25/12/2018','KT0137')	

INSERT INTO CTTHUE VALUES (1,'X2739',2)		
INSERT INTO CTTHUE VALUES (1,'X2719',1)		
INSERT INTO CTTHUE VALUES (2,'X2739',5)		

ALTER TABLE E_BILL ADD CONSTRAINT FK_MAKT FOREIGN KEY (MAKT) REFERENCES KHACHTHUE(MAKT);
ALTER TABLE CTTHUE ADD CONSTRAINT FK_SOHD FOREIGN KEY (SOHD) REFERENCES E_BILL(SOHD);
ALTER TABLE CTTHUE ADD CONSTRAINT FK_MAXE FOREIGN KEY (MAXE) REFERENCES XEMAY(MAXE);

-- cau 3
ALTER TABLE XEMAY ADD CONSTRAINT CHECK_TINHTRANG CHECK (TINHTRANG IN ('Con','Gan het','Het'));

-- cau 5
SELECT X.MAXE 
FROM E_BILL E , CTTHUE C, XEMAY X
WHERE E.SOHD = C.SOHD AND X.MAXE = C.MAXE AND MONTH(NGTHUE) = 12 AND YEAR(NGTHUE) = 2018
ORDER BY X.DUNGTICH;

--CAU 6
SELECT MAXE
FROM E_BILL E, CTTHUE C
WHERE E.SOHD = C.SOHD AND YEAR(NGTHUE) = 2018
GROUP BY MAXE
HAVING SUM(SL) >= ALL(SELECT SUM(SL)
						FROM E_BILL E, CTTHUE C
						WHERE E.SOHD = C.SOHD AND YEAR(NGTHUE) = 2018
						GROUP BY MAXE);

-- CAU 7 
SELECT MAKT
FROM XEMAY X, E_BILL E , CTTHUE C
WHERE X.MAXE = C.MAXE AND E.SOHD = C.SOHD AND DUNGTICH >= 100
EXCEPT
SELECT MAKT
FROM XEMAY X, E_BILL E , CTTHUE C
WHERE X.MAXE = C.MAXE AND E.SOHD = C.SOHD AND DUNGTICH<100


-- CAU 8
SELECT MAKT, TENKT
FROM KHACHTHUE K 
WHERE YEAR(NGSINH) = 1999 AND
NOT EXISTS (SELECT *
			FROM XEMAY X
			WHERE DUNGTICH >= 150
			AND NOT EXISTS (SELECT * 
							FROM E_BILL E,CTTHUE C
							WHERE E.SOHD = C.SOHD AND K.MAKT = E.MAKT AND C.MAXE = X.MAXE));

-- CAU 4
CREATE TRIGGER R_KT
ON KHACHTHUE
FOR UPDATE
AS
BEGIN
	DECLARE @ngsinh smalldatetime ,@makt char(6), @ngthue smalldatetime
	SELECT @ngsinh=NGSINH , @makt = MAKT FROM inserted
	SELECT @ngthue = NGTHUE FROM E_BILL WHERE MAKT = @makt
	IF @ngthue <= @ngsinh
	BEGIN
		PRINT N'Ngày thuê của khách thuê phải lớn hơn ngày sinh của người đó'
		ROLLBACK TRAN
	END
END

CREATE TRIGGER R_EBILL
ON E_BILL
FOR UPDATE,INSERT
AS
BEGIN
	DECLARE @ngsinh smalldatetime ,@makt char(6), @ngthue smalldatetime
	SELECT @ngthue=NGTHUE , @makt = MAKT FROM inserted
	SELECT @ngsinh = NGSINH FROM KHACHTHUE WHERE MAKT = @makt
	IF @ngthue <= @ngsinh
	BEGIN
		PRINT N'Ngày thuê của khách thuê phải lớn hơn ngày sinh của người đó'
		ROLLBACK TRAN
	END
END

