-- PHAN 2
-- CAU 1 
UPDATE GIAOVIEN
SET HESO = HESO + 0.2
WHERE MAGV IN ( SELECT TRGKHOA
				FROM KHOA
);

ALTER TABLE HOCVIEN ADD GHICHU varchar(1024);
ALTER TABLE HOCVIEN ADD DIEMTB decimal(4,2);
ALTER TABLE HOCVIEN ADD XEPLOAI varchar(10);

-- CAU 2
UPDATE HOCVIEN
SET DIEMTB = (
    SELECT AVG(KETQUATHI.DIEM) 
    FROM KETQUATHI
    WHERE KETQUATHI.MAHV = HOCVIEN.MAHV 
    AND KETQUATHI.MAMH IN (
        SELECT MAMH
        FROM KETQUATHI AS subKQ
        WHERE subKQ.MAHV = HOCVIEN.MAHV
        GROUP BY subKQ.MAMH
        HAVING MAX(subKQ.LANTHI) = KETQUATHI.LANTHI 
    )
);


-- CAU 3
UPDATE HOCVIEN
SET GHICHU = 'Cam thi'
WHERE MAHV IN  (
	SELECT MAHV
	FROM KETQUATHI
	WHERE LANTHI = 3 AND DIEM < 5.0
);

--CAU 4
UPDATE HOCVIEN
SET XEPLOAI = CASE
	WHEN DIEMTB >= 9 THEN 'XS'
	WHEN DIEMTB >=8 AND DIEMTB <9 THEN 'G'
	WHEN DIEMTB >=6.5 AND DIEMTB <8 THEN 'K'
	WHEN DIEMTB >=5 AND DIEMTB<6.5 THEN 'TB'
	ELSE 'Y'
END;

-- PHAN III
-- CAU 6
SELECT TENMH 
FROM MONHOC
WHERE MAMH IN (SELECT MAMH
				FROM GIANGDAY GD JOIN GIAOVIEN GV
				ON GD.MAGV = GV.MAGV
				WHERE GV.HOTEN = 'Tran Tam Thanh' AND GD.HOCKY = 1 AND NAM = 2006
);

--CAU 7
SELECT TENMH ,MAMH
FROM MONHOC
WHERE MAMH IN (
				SELECT MAMH
				FROM GIANGDAY GD
				WHERE GD.MAGV =  (SELECT MAGVCN FROM LOP WHERE MALOP ='K11') AND GD.HOCKY = 1 AND NAM = 2006
);

--CAU 8
SELECT HV.HO, HV.TEN
FROM LOP L JOIN HOCVIEN HV
ON L.TRGLOP = HV.MAHV
WHERE L.MALOP = (
		SELECT MALOP
		FROM GIANGDAY GD JOIN MONHOC MH
		ON GD.MAMH = MH.MAMH
		WHERE MH.TENMH = 'Co So Du Lieu' AND MAGV = (SELECT MAGV FROM GIAOVIEN WHERE HOTEN='Nguyen To Lan')
);

--Cau 9 
SELECT MAMH, TENMH
FROM MONHOC
WHERE MAMH IN (
	SELECT MAMH_TRUOC
	FROM DIEUKIEN
	WHERE MAMH = (
		SELECT MAMH
		FROM MONHOC
		WHERE TENMH = 'Co So Du Lieu'
	)
);

--CAU 10
SELECT MAMH,TENMH
FROM MONHOC
WHERE MAMH IN (
	SELECT MAMH
	FROM DIEUKIEN
	WHERE MAMH_TRUOC = (
			SELECT MAMH
			FROM MONHOC
			WHERE TENMH = 'Cau Truc Roi Rac'
	)
);

--Cau 11
SELECT HOTEN
FROM GIAOVIEN
WHERE MAGV IN (
		SELECT MAGV
		FROM GIANGDAY
		WHERE MALOP = 'K11' AND HOCKY = 1 AND NAM = 2006
)
INTERSECT
SELECT HOTEN
FROM GIAOVIEN
WHERE MAGV IN (
		SELECT MAGV
		FROM GIANGDAY
		WHERE MALOP = 'K12' AND HOCKY = 1 AND NAM = 2006
);

--CAU 12
SELECT MAHV, HO, TEN
FROM HOCVIEN
WHERE MAHV IN (
	SELECT MAHV
	FROM KETQUATHI
	WHERE LANTHI = 1 AND KQUA = 'Khong Dat' AND MAMH = (
														SELECT MAMH
														FROM MONHOC
														WHERE TENMH = 'Co So Du Lieu'
														)
)
EXCEPT
SELECT MAHV, HO, TEN
FROM HOCVIEN
WHERE MAHV IN (
	SELECT MAHV
	FROM KETQUATHI
	WHERE LANTHI = 2  AND MAMH = (
									SELECT MAMH
									FROM MONHOC
									WHERE TENMH = 'Co So Du Lieu'
						)
);

-- CAU 13
SELECT MAGV, HOTEN
FROM GIAOVIEN
EXCEPT
SELECT MAGV, HOTEN
FROM GIAOVIEN
WHERE MAGV IN (
		SELECT MAGV
		FROM GIANGDAY
);

--CAU 14
SELECT MAGV, HOTEN
FROM GIAOVIEN
EXCEPT
SELECT MAGV, HOTEN
FROM GIAOVIEN
WHERE MAGV IN (
		SELECT MAGV
		FROM GIANGDAY
		WHERE MAMH IN (
					SELECT MAMH
					FROM MONHOC
					WHERE MAKHOA = GIAOVIEN.MAKHOA
		)
);

--CAU 15
SELECT HO,TEN, MAHV
FROM HOCVIEN
WHERE MALOP = 'K11' AND MAHV IN (
		SELECT MAHV
		FROM KETQUATHI
		WHERE (LANTHI = 3 AND KQUA = 'Khong Dat') OR 
		(LANTHI = 2 AND DIEM = 5.0 AND MAMH = 'CTRR')
);

-- CAU 16
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE GV.MAGV IN (
    SELECT GD.MAGV
    FROM GIANGDAY GD
    JOIN MONHOC MH ON GD.MAMH = MH.MAMH
    WHERE MH.MAMH = 'CTRR'
    GROUP BY GD.MAGV, GD.HOCKY, GD.NAM
    HAVING COUNT(DISTINCT GD.MALOP) >= 2
);

-- CAU 17
SELECT HOCVIEN.MAHV, HOCVIEN.HO, HOCVIEN.TEN, KETQUATHI.DIEM
FROM HOCVIEN
JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
WHERE KETQUATHI.MAMH = 'CSDL'
AND KETQUATHI.LANTHI = (
    SELECT MAX(LANTHI) 
    FROM KETQUATHI
    WHERE MAHV = HOCVIEN.MAHV
    AND MAMH = 'CSDL'
);

-- CAU 18
SELECT HOCVIEN.MAHV, HOCVIEN.HO, HOCVIEN.TEN, KETQUATHI.DIEM
FROM HOCVIEN
JOIN KETQUATHI ON HOCVIEN.MAHV = KETQUATHI.MAHV
WHERE KETQUATHI.MAMH = 'CSDL'
AND KETQUATHI.DIEM = (
    SELECT MAX(DIEM) 
    FROM KETQUATHI
    WHERE MAHV = HOCVIEN.MAHV
    AND MAMH = 'CSDL'
);